### PR TITLE
replace all `fcp template` or `fcp device template` to new name

### PR DESCRIPTION
**Pull request by IBMCaoBiao**
replace all `fcp template` or `fcp device template` to `FCP Multipath Template`

Signed-off-by: CaoBiao <bjcb@cn.ibm.com>

### CODE REVIEW

**Review by dongyanyang — COMMENTED** [review]
an FCP multipath template -> a FCP multipath template

**Comment by IBMCaoBiao** [comment]
> an FCP multipath template -> a FCP multipath template

done.

**Review by dongyanyang — APPROVED** [review]
Let's hold this for a while

**Review by jackydalong — COMMENTED** [review]
lgtm

**Pull request merged**
