### PR TITLE
Add support for comment in user direct

### PR DESCRIPTION
**Pull request by santhosh-sloka**
To Support comments in user directory, It is discussed in detail in case " https://github.ibm.com/zvc/planning/issues/18693 "

--signed off : [ssanthosh@in.ibm.com](mailto:ssanthosh@in.ibm.com)

### CODE REVIEW

**Comment by santhosh-sloka** [comment]
Dear @SeanHQF @jichenjc - FYI 

@jichenjc - As discussed created a separte PR for the comment support, thanks

**Comment by jichenjc** [comment]
@SeanHQF please review so we can merge this

**Comment by santhosh-sloka** [comment]
> @SeanHQF please review so we can merge this

@jichenjc @SeanHQF - We are testing the existing scenario , will confirm by this week or the merger of PR : https://github.com/openmainframeproject/feilong/pull/834, https://github.com/openmainframeproject/feilong/pull/833 and https://github.ibm.com/zvc/nova-icic/pull/102

**Comment by SeanHQF** [comment]
Why not combine this with https://github.com/openmainframeproject/feilong/pull/833?

**Comment by SeanHQF** [comment]
Generally I am ok with the code change, but since the change is small, so may be combined together with clear comment or 2 commits.

**Comment by jichenjc** [comment]
no, We should not do combination if it's not related 2 commits
@SeanHQF that one is for CPU share and this one is for comment?

**Comment by SeanHQF** [comment]
> no, We should not do combination if it's not related 2 commits @SeanHQF that one is for CPU share and this one is for comment?

ok

**Review by SeanHQF — APPROVED** [review]

**Pull request merged**
