### PR TITLE
update path value of FCP in database when its value changed

### PR DESCRIPTION
**Pull request by SharpRazor**
Signed-off-by: bjcb <bjcb@cn.ibm.com>

### CODE REVIEW

**Comment by SharpRazor** [comment]
### the old database:
```
sqlite> select * from fcp;
1c12|M54CB004|0|0|1|
1c11||0|0|1|
1c14|M54CB004|0|0|1|
1c10||0|0|1|
1c13||0|0|1|
1b11||0|0|0|
1b12||0|0|0|
1b10|M54CB004|0|0|0|
1b13||0|0|0|
1b14||0|0|0|
sqlite> 
```
### then edit to new fcp_list 
```
[root@114-cmp-cb zvmsdk]# cat /etc/zvmsdk/zvmsdk.conf| grep fcp_list
fcp_list=1C10-1C14;1D10-1D14
# fcp_list example:
[root@114-cmp-cb zvmsdk]# 
```

### then attach a volume:
the new database:
```
sqlite> select * from fcp;
1c12|M54CB004|0|0|0|
1c11||0|0|0|
1c14|M54CB004|0|0|0|
1c10||0|0|0|
1c13|M54CB004|1|1|0|
1d13||0|0|1|
1d12||0|0|1|
1d14||0|0|1|
1d10||0|0|1|
1d11|M54CB004|1|1|1|
sqlite> 
```

**Comment by SharpRazor** [comment]
@dongyanyang @bjhuangr please help review, thanks.

**Review by dongyanyang — APPROVED** [review]
@SharpRazor please also test edit from single path to multipath.

**Comment by SharpRazor** [comment]
edit from fcp_list `1C10-1C14;1D10-1D14` to `1C10-1C14,1D10-1D14`
### before edit:
```
sqlite> select * from fcp;
1c12|M54CB004|0|0|0|
1c11||0|0|0|
1c14|M54CB004|0|0|0|
1c10||0|0|0|
1c13|M54CB004|1|1|0|
1d13||0|0|1|
1d12||0|0|1|
1d14||0|0|1|
1d10||0|0|1|
1d11|M54CB004|1|1|1|
sqlite>
```
### after edit:
the fcp_list:
```
[root@114-cmp-cb databases]# cat /etc/zvmsdk/zvmsdk.conf | grep fcp_list
fcp_list=1C10-1C14,1D10-1D14
# fcp_list example:
[root@114-cmp-cb databases]#
```
the database status after detaching a volume:
```
sqlite> select * from fcp;
1c12|M54CB004|0|0|0|
1c11||0|0|0|
1c14|M54CB004|0|0|0|
1c10||0|0|0|
1c13|M54CB004|0|0|0|
1d13||0|0|0|
1d12||0|0|0|
1d14||0|0|0|
1d10||0|0|0|
1d11|M54CB004|0|0|0|
sqlite>
```

### edit fcp_list from `1C10-1C14,1D10-1D14` to `1C10-1C14;1D10-1D14`
the fcp_list
```
[root@114-cmp-cb databases]# cat /etc/zvmsdk/zvmsdk.conf | grep fcp_list
fcp_list=1C10-1C14;1D10-1D14
# fcp_list example:

```
the database status after attaching a volume:
```
sqlite> select * from fcp;
1c12|M54CB004|0|0|0|
1c11||0|0|0|
1c14|M54CB004|0|0|0|
1c10||0|0|0|
1c13|M54CB004|1|1|0|
1d13||0|0|1|
1d12||0|0|1|
1d14|M54CB004|1|1|1|
1d10||0|0|1|
1d11|M54CB004|0|0|1|
sqlite>
```

**Review by bjhuangr — APPROVED** [review]

**Pull request merged**
