### PR TITLE
Clarify architecture schema

### PR DESCRIPTION
**Pull request by Bischoff**
Fix issue #782

(edited)

The Linux guests managed by feilong were absent from the schema, while they are the final goal. This PR adds them and also shows that they are accessed by IUCV too.

also:
* removed the red underlining from spelling corrector
* shortened some existing texts
* added a legend "HTTP protocol" to blue arrow on top
* removed black spot on top

### CODE REVIEW

**Comment by bjhuangr** [comment]
All looks good to me, except: `the box on the right is for a Linux guest`

I think in original diagram, the box on the right is SMAPI servers. feilong talks to SMAPI request server via IUCV channel.

@jichenjc need your comment as you drawed this :)

**Comment by jichenjc** [comment]
SMAPI is part of z/VM ==> SMAPI is a set of CMS VM , it's running REXX and provide socket connection , you can use IUCV or TCPIP to connect to the socket server side, so I Think that part is correct ...

**Comment by Bischoff** [comment]
OK, that was my original question in #782 and also in the discussion for #751.

So let's keep the content of the right box. But there's still something I'd like to correct.

"you **can** use IUCV or TCPIP to connect to the socket server side" yes, but if I understood well, feilong uses TCP/IP to do that (via zthin). But the schema shows IUCV.

I therefore suggest to redo my work, keeping the box on the right, but changing "IUCV" to "TCP/IP".

Would that work?

**Comment by jichenjc** [comment]
>>>"you can use IUCV or TCPIP to connect to the socket server side" yes, but if I understood well, feilong uses TCP/IP to do that (via zthin). But the schema shows IUCV.

SMAPI allow TCPIP and IUCV
feilong is using IUCV (so we can bypass the setting of z/VM IP, port etc configuration) ,just use IUCV to directly talk to the z/VM that compute node inside is running the feilong

**Comment by bjhuangr** [comment]
Yes, feilong is using IUCV, not TCP/IP

**Comment by Bischoff** [comment]
ok, I can do a schema with 3 boxes that summarizes it all:
1. at the center, BYOS Linux + feilong
2. at the left, guest Linux + user workflows
3. at the right, CMS + SMAPI

* between 1. and 2., an IUCV connection
* between 2. and 3., an IUCV connection too

would that be okay?

**Comment by jichenjc** [comment]
yes, good change

@bjhuangr thoughts?

**Comment by bjhuangr** [comment]
> ok, I can do a schema with 3 boxes that summarizes it all:
> 
> 1. at the center, BYOS Linux + feilong
> 2. at the left, guest Linux + user workflows
> 3. at the right, CMS + SMAPI
> 
> * between 1. and 2., an IUCV connection
> * between 2. and 3., an IUCV connection too
> 
> would that be okay?

Looks good to me. Thanks for refine the diagram.

**Comment by Bischoff** [comment]
OK, new version is in this PR.

Is it OK?

**Pull request merged**
