### PR TITLE
[master]add missing parameter in detach rollback

### PR DESCRIPTION
**Pull request by SharpRazor**
found missing need_restart in detach rollback

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

### CODE REVIEW

**Comment by SharpRazor** [comment]
@dongyanyang @bjhuangr need your review.

**Comment by jichenjc** [comment]
@SharpRazor is it possible to add one line UT such as 
xxx.assertCalledwith(xxxx, yyy,zzzz) so that we can make sure this kind of error will not happen again?

**Comment by SharpRazor** [comment]
> @SharpRazor is it possible to add one line UT such as
> xxx.assertCalledwith(xxxx, yyy,zzzz) so that we can make sure this kind of error will not happen again?

OK, I will add.

**Comment by SharpRazor** [comment]
@jichenjc  UT done.

**Pull request merged**
