### PR TITLE
Support sending transportfiles without a deploy action

### PR DESCRIPTION
**Pull request by jasealpers**
This change allows custom actions to be driven via the reader to zvmguestconfigure on the guest after the initial deploy.

### CODE REVIEW

**Comment by jichenjc** [comment]
sorry, I don't fully understand the purpose of the PR
could you please help to open an issue and describe the reason you want to make the change? thanks

**Comment by jasealpers** [comment]
It seems issues are not enabled for this github repo?

The issue is that we need a way to send transportfiles to a guest without using the deploy action since that will also deploy and potentially overwrite disks.  The change allows us to use the zvmguestconfigure action on IPL to make changes to the guest after the initial deploy.

**Comment by bjhuangr** [comment]
Thanks for the PR.

We used to have a discussion on whether zvm cloud connector should expose such an API to punch files to the guest VM. We've got agreement that it's insecure to expose the punch file API, and limit the punch action internal in zvm cloud connector. `zvmguestconfigure` act as just an one shot initial tool, not an agent daemon.

**Comment by jasealpers** [comment]
I suspect when you indicate that it's insecure to expose the punch file API that you don't want those with access to the admin token to also have access to the provisioned guests.  However, this is possible with existing interfaces.  The "capture guest" API followed by the "deploy guest" API with transportfiles exposes the provisioned guests in the same way from a security perspective.

Perhaps additional security needs to be added so that only some users can take actions that utilize the punch file API?

As a separate note, just for clarity it's worth pointing out that this PR does not change `zvmguestconfigure` to be an agent daemon.  It only exposes the punch file API separate from the deploy API.

**Comment by bjhuangr** [comment]
In current implementation, punch files only happens inner zvm cloud connector, not allowed punch any files to a deployed guest at any time.

Could you please help us to understand the use case that why you want add this API? Any workarounds available?

**Comment by jasealpers** [comment]
In the current implementation, you can capture a disk and then re-deploy that disk to the existing guest in order to punch a file to an already deployed guest.  This effectively lets anyone with access punch a file to an existing guest, but only in a disruptive manner.

As far as workarounds, we did consider creating a 1 cyl minidisk for each guest that contains no data.  Then we could use the deploy guest API for that minidisk just to punch the file, but we're not keen on managing loads of small disks.

Two immediate use cases for us...
- Manage lvm on the guest.  We want to allow users to dynamically add minidisks as PVs and manage the related VGs/LVs.
- Centralize authentication on the guests (ids/passwords/keys) such that users can manage credentials for all their guests in a single location (single user action may drive changes on multiple guests)

**Comment by bjhuangr** [comment]
```Two immediate use cases for us...

    Manage lvm on the guest. We want to allow users to dynamically add minidisks as PVs and manage the related VGs/LVs.
    Centralize authentication on the guests (ids/passwords/keys) such that users can manage credentials for all their guests in a single location (single user action may drive changes on multiple guests)
```
For case 1, I'd suggest to add new API to add disks for active guests. For case 2, does vm intial tools like cloud-init help in this case? Which is able to setup initial user and password for the guest.

**Comment by jichenjc** [comment]
@jasealpers as discussed ,please help to update the PR (currently it's also contains conflict, maybe you need some rebase/merge as well) thanks a lot

**Comment by jasealpers** [comment]
Removed the conflict and added logic to support parameterized scripts.

There is also one other use case not mentioned above that we will use this service to accomplish - automated maintenance of linux guest images.

**Comment by bjhuangr** [comment]
close the inactive PR

**Pull request closed without merging**
