### PR TITLE
[master] Support dest_zcc_userid to be None

### PR DESCRIPTION
**Pull request by SeanHQF**
So that no need to set the userid for the onboarded guest
which has no permission. Without this, LGR can still work.

Signed-off-by: QingFeng Hao <haoqf@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by SeanHQF** [comment]
@bjhuangr @jichenjc @zhshuj pls help review

**Comment by zhshuj** [comment]
LGTM.
But this solution still has the limitation that if we further do any operations(although we don't know what it would be now) to onboarded VM that requires IUCV authorization, then it would encounter error.

**Comment by SeanHQF** [comment]
> LGTM. But this solution still has the limitation that if we further do any operations(although we don't know what it would be now) to onboarded VM that requires IUCV authorization, then it would encounter error.

Yes, but right now no good solution for the onboarded VM.

**Comment by zhshuj** [comment]
> > LGTM. But this solution still has the limitation that if we further do any operations(although we don't know what it would be now) to onboarded VM that requires IUCV authorization, then it would encounter error.
> 
> Yes, but right now no good solution for the onboarded VM. And this doesn't make it worse as the userid of onboarded VM's iucv isn't the same as the compute node.

Yes. Agree

**Review by bjhuangr — APPROVED** [review]

**Pull request merged**
