### PR TITLE
[master] fix the comment of default_admin_userid

### PR DESCRIPTION
**Pull request by SeanHQF**
The value of default_admin_userid can't be empty, otherwise, VM deploy
will fail. But it can be space.

### CODE REVIEW

**Comment by SeanHQF** [comment]
@jichenjc @bjhuangr @dongyanyang pls help review, thx

**Comment by jichenjc** [comment]
what's the meaning of blank ? if it's blank, what will happen? 
I am curious why we do in this way
we should trim the blank .. leave a blank here is very error leading

**Comment by SeanHQF** [comment]
> what's the meaning of blank ? if it's blank, what will happen?
> I am curious why we do in this way
> we should trim the blank .. leave a blank here is very error leading

Space can make vm deploy succeed.

**Comment by jichenjc** [comment]
I am not sure I get your point 

space is ok , but what's the meaning space? we need know the user impact instead of 'it works'

**Comment by SeanHQF** [comment]
> I am not sure I get your point
> 
> space is ok , but what's the meaning space? we need know the user impact instead of 'it works'

Maybe it will forbid the VM's logon from 3270, I'll check it.

**Comment by SeanHQF** [comment]
> I am not sure I get your point
> 
> space is ok , but what's the meaning space? we need know the user impact instead of 'it works'

space forbids the VM's access from 3270 after checking the link from Rui.

**Comment by SeanHQF** [comment]
@jichenjc @bjhuangr @dongyanyang pls help review and I tested with the latest build and the result is in issue 4070, thx

**Review by bjhuangr — APPROVED** [review]

**Pull request merged**
