### PR TITLE
Package installation doc for setting up web server 

### PR DESCRIPTION
**Pull request by aazam-gh**
Added installation instructions for the RHEL package.

### CODE REVIEW

**Review by Bischoff — CHANGES_REQUESTED** [review]
unfinished, we need at least instructions how to download the packages

**Comment by bjhuangr** [comment]
@aazam-gh still WIP?

**Comment by aazam-gh** [comment]
@bjhuangr Yes, a few more additions to be made

**Comment by Bischoff** [comment]
@bjhuangr we are experiencing difficulties with the firewall setup. We'd like it to work automatically. Based on the outcome, the instructions might slightly change.

Also, we don't have yet a download area for the built packages. We're working on that too.

**Comment by bjhuangr** [comment]
@Bischoff thanks for sharing the context

**Comment by aazam-gh** [comment]
PR is ready to be merged.

**Review by bjhuangr — APPROVED** [review]

**Pull request merged**
